from typing import TypedDict, Optional, Annotated, List, Literal




class AgentState(TypedDict):

    question: str               # question by user
    sql_query: Optional[str]              # query generated by agent
    query_result: Optional[str]           # query result after execution
    final_answer: Optional[str]           # final answer in readable format after executing the query

    error: Optional[str]                  # error occured while executing query
    iteraion: Optional[int]               # # of iteration.    
    
    needs_graph: Optional[bool]           # variable to store if graph is required
    graph_type: Optional[str]             # if graph is required, type of graph to plot (bar chart, pie chart etc)
    graph_json: Optional[str]             # graph data to send to feontend
    is_in_scope: Optional[bool]           # to decide whether asked question is in scope as per db or out of scope 