"""
this agent automatically attempts to fix bad/wrong SQL queries

Input:
error: SQL execution error
SQL Query: Query generated by sql_generation_agent
Question: Original question asked by user

Output:
new sql_query: newly generated SQL query by analyzing error
clears error
iteration: increment in iteration

Retries:
- This agent tries to fix error three times. 
- If fails after three attempts -> Returns apology message in final_answer
"""


import os
import sys
import sqlite3
import json

from pydantic import Field, BaseModel

sys.path.append(os.path.abspath("../"))

from State_Schema.state_schema import AgentState
from State_Schema.schema_info import SCHEMA_INFO

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.prompts import ChatPromptTemplate
from langchain_ollama import ChatOllama

llm = ChatOllama(model="qwen3:8b")

class ErrorAgentOutputFormat(BaseModel):

    error_reason: str = Field(..., description="reason why the error occured")
    corrected_sql_query: str = Field(..., description="corrected query")

structured_llm = llm.with_structured_output(ErrorAgentOutputFormat)

prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are an expert SQL query generator. Your job is to analyze the error while executing the SQL query."
            "Analyze the error and regenerate correct SQL query. In error_reason, mention error reason and in corrected_sql_query give only SQL query"
        ),
        (
            "human",
            "Question: {question}"
            "SQL Query: {sql_query}"
            "Error: {error}"
        )
    ]
)


chain = prompt | structured_llm


def error_agent(state: AgentState):
    """handles erorrs in sql execution and attempts to generate new query"""

    output = chain.invoke(
        {
            "question": state["question"],
            "sql_query": state["sql_query"],
            "error": state["error"]
        }
    )

    state["sql_query"] = output.corrected_sql_query
    state["error"] = output.error
    state['iteraion'] = state.get("iteration", 0) + 1

    return state




if __name__ == "__main__":
    initial_state = {
    "question": "what are the top 5 states by number of customers?",
    "error": "",
    "sql_query": """SELECT customer_state, COUNT(*) AS num_customers\nFROM customers\nGROUP BY customer_state\nORDER BY num_customers DESC\nLIMIT 0"""
    }

    output = error_agent(initial_state)
    print(output)
