import os
import sys
import sqlite3
import json

sys.path.append(os.path.abspath("../"))

from State_Schema.state_schema import AgentState
from State_Schema.schema_info import SCHEMA_INFO


db_path = "../ecommerce.db"



def execute_query(state: AgentState):
    """
    executes the SQL query generated by SQL generation agent and return the result in json format
    """

    sql_query = state["sql_query"]

    try:

        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()

        sql_statements = []

        for stmt in sql_query.split(";"):
            if stmt.strip():
                sql_statements.append(stmt.strip())
        
        all_results = []

        for count, statements in enumerate(sql_statements):
            cursor.execute(statements)
            result = cursor.fetchall()

            if result:
                column_names = [description[0] for description in cursor.description]

                # converting to list of dictionaries
                formatted_results = []

                for row in result[:100]:
                    formatted_results.append(dict(zip(column_names, row)))

                # case to handle multiple queries
                if len(sql_statements) > 1:
                    all_results.append(
                        {
                            f"query_{count+1}": formatted_results,
                            f"query_{count+1}_sql": statements
                        }
                    )

                else:
                    all_results=formatted_results
        conn.close()

        if not all_results:
            state["query_result"]="No Results Found"

        else:
            state["query_result"]=json.dumps(all_results, indent=4)

        state["error"]=""

    except Exception as e:
        state["error"]=f"SQL Query Execution Error: {e}"
        state["query_result"]=""

    return state



if __name__=="__main__":

    sql_query="SELECT customer_state, COUNT(*) AS num_customers\nFROM customers\nGROUP BY customer_state\nORDER BY num_customers DESC\nLIMIT 5"

    initial_state = {
        "question": [],
        "sql_query": sql_query
    }

    print(
        execute_query(initial_state)
    )