"""
takes query_result, graph_type and output data as input and 
generates  graph and return json graph
"""


import os
import sys
sys.path.append(os.path.abspath("../"))
import json

from langchain_ollama import ChatOllama
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate

from State_Schema.state_schema import AgentState

import pandas as pd
from pydantic import BaseModel, Field
from loguru import logger

# llm = ChatOllama(model="qwen3:8b")

os.environ['OPENAI_API_KEY'] = ""

llm = ChatOpenAI(model='gpt-4o')


class PlotylyCode(BaseModel):

    code: str = Field(..., description="python-plotly code generated using given dataframe. Give the code directly. Don't give anything else.")

structured_llm = llm.with_structured_output(PlotylyCode)


prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "Generate a python-plotly code to visualize following data"
            """Requirements:
            1. Use plotly.graph_objects or plotly.express
            2. The data is already loaded as 'df' (a pandas DataFrame).
            3. Create an appropriate graph type chart
            4. Limit data to top 20 rows if there are many rows
            5. Add proper titles, labels, and formatting
            6. The figure variable must be named 'fig'
            7. Return ONLY the Python code, no explanations or markdown
            8. Do NOT include any import statements
            9. Do NOT include code to show the figure (no fig.show())
            10. Make the visualization visually appealing with appropriate colors and layout
            11. Update the layout for better interactivity (hover info, responsive sizing)
            12. Return only python-plotly code. Don't return anything else
            13. Don't set responseive=True and also set autosize=True optionally.
            """
        ),
        (
            "human",
            "Question: {question}"
            "Graph Type: {graph_type}"
            "Columns: {columns}"
            "Sample Data (first 5 rows): {sample_data}"
            "Total Rows: {total_rows}"
        )
    ]
)

chain = prompt | structured_llm

def visualization_agent(state: AgentState):
    """
    generate a graph visualization from a query results using ploytly code
    generated by LLM
    """

    query_result = state["query_result"]
    graph_type = state["graph_type"]
    question = state["question"]

    try:
        results = json.loads(query_result)
        if not results or len(results) == 0:
            state["graph_json"] = ""
            return state
        
        df = pd.DataFrame(results)
        columns = df.columns.to_list()
        sample_data = df.head(5).to_dict("records")

        print('before llm call')

        output = chain.invoke(
            {
                "question": question,
                "graph_type": graph_type,
                "columns": columns,
                "total_rows": len(df),
                "sample_data": json.dumps(sample_data, indent=4)
            }
        )

        print(output)

        plotly_code = output.code.strip()

        # creating execution environment
        exec_globals = {
            "df": df,
            "pd": pd,
            "json": json
        }

        import plotly
        import plotly.graph_objects as go
        import plotly.express as px
        exec_globals["go"] = go
        exec_globals["px"] = px
        exec_globals["plotly"] = plotly

        exec(plotly_code, exec_globals)

        fig = exec_globals.get("fig")

        if fig is None:
            raise ValueError("Generated code did not create a fig variable")

        graph_json = fig.to_json()
        logger.info(graph_json)

        state["graph_json"] = graph_json

    except Exception as e:
        print(f"Graph generation error: {e}")
        state["graph_json"] = ""
    
    return state



if __name__ == "__main__":

    state = {
        "question": "what are the top 5 states by number of customers?",
        "graph_type": "bar",
        # "columns": ["SP", "RJ", "MG", "RS", "PR"],
        "query_result": """[\n    {\n        "customer_state": "SP",\n        "num_customers": 41746\n    },\n    {\n        "customer_state": "RJ",\n        "num_customers": 12852\n    },\n    {\n        "customer_state": "MG",\n        "num_customers": 11635\n    },\n    {\n        "customer_state": "RS",\n        "num_customers": 5466\n    },\n    {\n        "customer_state": "PR",\n        "num_customers": 5045\n    }\n]""",
    }



    output = visualization_agent(state)
    print(output)